apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - name: nginx-port
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata: 
  name: nginx 
  labels: 
    app: nginx
spec: 
  ports: 
  - port: 3000
    targetPort: nginx-port 
  selector: 
    app: nginx 
  type: LoadBalancer